-- ============================================================================
-- DATABASE SCHEMA - Configuration Storage with Audit Trail
-- ============================================================================

-- Main configuration table
CREATE TABLE batch_configurations (
    id VARCHAR(100) PRIMARY KEY,
    source_system VARCHAR(50) NOT NULL,
    job_name VARCHAR(50) NOT NULL,
    transaction_type VARCHAR(20) DEFAULT '200',
    description VARCHAR(500),
    configuration_json CLOB NOT NULL,
    created_by VARCHAR(50) NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(50),
    modified_date TIMESTAMP,
    version INTEGER DEFAULT 1,
    enabled VARCHAR2(1) DEFAULT 'Y' CHECK (enabled IN ('Y', 'N')),
    UNIQUE(source_system, job_name, transaction_type)
);

-- Audit trail for all configuration changes
CREATE TABLE configuration_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id VARCHAR(100) NOT NULL,
    action VARCHAR(20) NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
    old_value CLOB,
    new_value CLOB,
    changed_by VARCHAR(50) NOT NULL,
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    change_reason VARCHAR(500),
    FOREIGN KEY (config_id) REFERENCES batch_configurations(id)
);

-- Source systems metadata (enhance existing or new table)
CREATE TABLE source_systems (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('ORACLE', 'SQLSERVER', 'FILE', 'API')),
    description VARCHAR(500),
    connection_string VARCHAR(1000),
    enabled VARCHAR2(1) DEFAULT 'Y' CHECK (enabled IN ('Y', 'N')),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    job_count INTEGER DEFAULT 0
);

-- Job definitions (link to existing FileConfig if exists)
CREATE TABLE job_definitions (
    id VARCHAR(100) PRIMARY KEY,
    source_system_id VARCHAR(50) NOT NULL,
    job_name VARCHAR(50) NOT NULL,
    description VARCHAR(500),
    input_path VARCHAR(1000),
    output_path VARCHAR(1000),
    query_sql CLOB,
    enabled VARCHAR2(1) DEFAULT 'Y' CHECK (enabled IN ('Y', 'N')),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    transaction_types VARCHAR(200), -- Comma-separated: "200,300,900"
    FOREIGN KEY (source_system_id) REFERENCES source_systems(id),
    UNIQUE(source_system_id, job_name)
);

-- Indexes for performance
CREATE INDEX idx_batch_config_system_job ON batch_configurations(source_system, job_name);
CREATE INDEX idx_config_audit_config_id ON configuration_audit(config_id);
CREATE INDEX idx_config_audit_date ON configuration_audit(change_date);
CREATE INDEX idx_job_definitions_system ON job_definitions(source_system_id);

-- Sample data
INSERT INTO source_systems (id, name, type, description, job_count) VALUES 
('hr', 'HR System', 'ORACLE', 'Human Resources System', 2),
('dda', 'DDA System', 'ORACLE', 'Demand Deposit Accounts', 3),
('shaw', 'SHAW System', 'SQLSERVER', 'SHAW Processing System', 1);

INSERT INTO job_definitions (id, source_system_id, job_name, description, transaction_types) VALUES
('hr-p327', 'hr', 'p327', 'HR P327 Processing', '200,900'),
('hr-p329', 'hr', 'p329', 'HR P329 Processing', '200'),
('dda-accounts', 'dda', 'accounts', 'Account Processing', '200,300,900'),
('shaw-processing', 'shaw', 'processing', 'Main Processing', '200');

COMMIT;